### ISSUE TITLE
News page with no articles is ugly

### ISSUE THREAD

**Issue by jgraycar** [calraijintaiko/caltaiko#19]
Not too important, since will never pop up on live site, but would be nice to fix.

**Comment by jgraycar** [comment]
![screen shot 2016-04-05 at 12 40 49 pm](https://cloud.githubusercontent.com/assets/7464841/14295754/c7f58dce-fb2b-11e5-91b2-38b0e1d19ddd.png)

**Comment by jgraycar** [comment]
Probably want to make it look like upcoming performances message:

![screen shot 2016-04-05 at 12 42 29 pm](https://cloud.githubusercontent.com/assets/7464841/14295794/ed496d0c-fb2b-11e5-85d4-a76dd5c95ba9.png)

**Comment by benortiz** [comment]
@jgraycar plz assign me

**Comment by benortiz** [comment]
`rm -rf /`
