### ISSUE TITLE
Add phone number field to Members model

### ISSUE THREAD

**Issue by jgraycar** [calraijintaiko/caltaiko#41]
This will only be displayed to logged in users, on a members modal view and the database page. It should be an optional attribute.

**Comment by jgraycar** [comment]
This includes updating the member form, the db seeder, and the member factory.

**Comment by jgraycar** [comment]
@benortiz how's this sound?

**Comment by jgraycar** [comment]
If we're gonna add phone numbers, might as well do go in 100% - let's ensure they're valid and store them in the db in E164 format using something like [phonelib](https://github.com/daddyz/phonelib) or [global_phone](https://github.com/sstephenson/global_phone).

**Comment by benortiz** [comment]
- [ ] Add and configure [phonelib](https://github.com/daddyz/phonelib)
- [ ] Create a migration
- [ ] Add to the members model with parsing and validation
- [ ] Input on the admin Members form (optional)
- [ ] Show on Member modal to logged in user
- [ ] Update the Member factory
- [ ] Update the db seeder
- [ ] Test??? omg how.

https://github.com/googlei18n/libphonenumber/blob/master/FALSEHOODS.md

**Comment by benortiz** [comment]
@jgraycar should the email be visible to logged in users too on the modal/profile? and what is the "database page"

**Comment by jgraycar** [comment]
Actually I was thinking about this, and I think it makes more sense to not display the phone number (or email address) on the modal after all. I don't think it's information that will be needed very often, so we can just keep it to only the database page. Which is `/members/database` 👍

**Comment by jgraycar** [comment]
Also, as it is right now, the actual individual member pages like `/member/joel-graycar` aren't actually linked to anywhere lol 😝  It's only the modals that are actually used. But it uses the same template as the modal, so any changes to one will show up in the other for free!

**Comment by benortiz** [comment]
@jgraycar oh wowe that data! okay no modal! what about on /members/member-name?

**Comment by benortiz** [comment]
oh. sooooooooo. don't add it there? lol

**Comment by jgraycar** [comment]
Haha yeah no need, I think keeping it only on the database page will be good enough

**Comment by benortiz** [comment]
aye aye captain!

**Comment by jgraycar** [comment]
🎅 🎅 🎅

**Comment by benortiz** [comment]
@jgraycar how many non-us numbers do you imagine having?

**Comment by benortiz** [comment]
@jgraycar I think I have it all working, but I am getting failing spec tests and not sure how to address them.

![image](https://cloud.githubusercontent.com/assets/681189/14417102/21917e7c-ff66-11e5-82b0-04b0d6caf2da.png)

**Comment by jgraycar** [comment]
@benortiz: probably none lol. If you want to, we could have a server-side validation that checks if a number is a US one, and fails with a relevant message otherwise. I don't think anyone trying to contact an alumni would bother with an international phone number haha.

Lemme checkout your commit and see if I can figure out your spec issue right now 👍

**Comment by benortiz** [comment]
@jgraycar any ideas? :/ I'll change it over to show the local version of numbers then :)

**Comment by jgraycar** [comment]
Ahhh my b, I still haven't given it a good look yet. I'll do that now!

**Comment by jgraycar** [comment]
@benortiz I think I've got it! I believe the issue is that Faker's generated phone numbers are just using three random numbers for the area code, and the validation is checking whether they are real zipcodes then failing when they aren't.

It should be fine to just hard code a valid phone number like so

    f.phone '(510) 999-9999'

and then we won't have that problem!

**Comment by jgraycar** [comment]
Can we also add a `before_save` callback to reformat the entered phone number into international format? That way they'll all be the same format in the db, so we don't end up with something like this:

![screen shot 2016-04-12 at 2 41 10 pm](https://cloud.githubusercontent.com/assets/7464841/14476458/ae9e86b4-00bc-11e6-85e2-e9f020d1fb25.png)

**Comment by benortiz** [comment]
@jgraycar perfect thank you!!!! I couldn't tell if it was that or if it was just me ><

re the before_save, `phonelib` is supposed to sanitize all phone numbers input from the form (ie store only the numbers). Is that not working or were these numbers inserted by some other method?

**Comment by jgraycar** [comment]
Huhh interesting. Those were entered through the form, so it looks like that sanitation isn't happening 😞

**Comment by benortiz** [comment]
💔  I'll see what I can do 💔

**Comment by jgraycar** [comment]
👌 👌

**Comment by benortiz** [comment]
@jgraycar I think I've addressed all the issues!!
