### ISSUE TITLE
Embed map on performance page

### ISSUE THREAD

**Issue by jgraycar** [calraijintaiko/caltaiko#65]
Let's embed a little Google Maps map on the performance page! Useful links:

1. https://github.com/alexreisner/geocoder
1. http://www.sitepoint.com/use-google-maps-rails/
1. https://github.com/apneadiving/Google-Maps-for-Rails

**Comment by benortiz** [comment]
@jgraycar what geo info do your performances have?

hehe hi

**Comment by jgraycar** [comment]
@benortiz lol we're going simple as can be :stuck_out_tongue: Single location marker FTW

**Comment by benortiz** [comment]
haha :smile: noice! and yee i in berkeley and down to game!!

**Comment by jgraycar** [comment]
:grin: :+1: :+1:

**Comment by benortiz** [comment]
Which issue should I jump in on? lol

**Comment by jgraycar** [comment]
Haha how big of a project do you wanna do? Start small or jump right in?

**Comment by benortiz** [comment]
start small plz. lol.

**Comment by jgraycar** [comment]
How about #19 ? Should be a pretty quick fix!
